services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '4000:4000'
    # volumes:
    #   - ./:/app
    #   - nodemodules:/app/node_modules
    command: npm run start:dev
    environment:
      - NODE_ENV=development
volumes:
  nodemodules: {}
